### ISSUE TITLE
部署报错：File not found

### ISSUE THREAD

**Issue by purezhi** [a132395/subconverter-vercel#1]
About 里的版本也是同样的。

**Comment by ChengMoo** [comment]
https://xxx.vercel.app/sub?target=clash&url=你的订阅地址

**Comment by ChengMoo** [comment]
使用帮助，请右转原项目：https://github.com/tindy2013/subconverter
本项目仅提供部署

**Comment by purezhi** [comment]
转换确实是正常的，只是原来的版本根地址会显示版本号，现在提示File not found.
